lista_de_palavras = {'aranha':"sobe nas paredes",
'arara':'parece papagaio',
'asno': 'sinonimo de burro',
'atum': 'comum em sushi',
'avestruz': 'uma ave gigante',
'bode' : 'pequeno de chifre',
'boi': 'muito comum em açougue',
'borboleta':'asas coloridas',
'boto':'mítico como golfinho',
'búfalo':'uma espécie de bovino',
'capivara': 'Roedor',
'cachorro': 'melhor amigo',
'camelo':'vende produtos piratas',
'cabra': 'fêmea do bode',
'cavalo': 'O do hércules tinha asas',
'esquilo': 'gosta de nozes',
'elefante': 'sagrado na índia',
'flamingo' : 'Ave Rosa',
'foca': 'bola no nariz',
'gaivota': 'ave marinha',
'golfinho':'mamifero aquático',
'gorila':'king kong',
'guaxinim': 'guardiões da galaxia',
'gazela': 'bamby',
'galinha': 'cocó'}
